---
deployment:
  tasks:
    - export DEPLOYPATH=/home/fvkpphtr/public_html/
    - /bin/cp -R *.php $DEPLOYPATH
    - /bin/cp -R *.htm $DEPLOYPATH
    - /bin/cp -R TEMPLATES/ $DEPLOYPATH
    - /usr/bin/find includes/ -maxdepth 1 -not -name "conf.php" -type f -exec /bin/cp {} $DEPLOYPATH/{} \;
    - /bin/cp -R data/ $DEPLOYPATH
    - /bin/cp -R keon/ $DEPLOYPATH
    - /bin/cp -R utils/ $DEPLOYPATH
